<?php

//ini_set('display_errors', 1);
//error_reporting(E_ALL);
//$link=odbc_pconnect("control_filas","Apl_control_filas","Na5*1iW.Ckl-zX");
$link=odbc_pconnect("control_filas1","Apl_control_filas1","Na5*1iW.Ckl-zX");
//$link=odbc_pconnect("control_filas","sa","");
	
//echo $link;
//$link=odbc_pconnect("control_filas2","Apl_control_filas2","Na5*1iW.Ckl-zX");
//$link=odbc_pconnect("control_filas3","Apl_control_filas3","Na5*1iW.Ckl-zX");
//$link=odbc_pconnect("control_filas4","Apl_control_filas4","Na5*1iW.Ckl-zX");
//$link=odbc_pconnect("control_filas5","Apl_control_filas5","Na5*1iW.Ckl-zX");

//$link=odbc_pconnect("control_filas","sa","conzt98!");

//echo 'link '.$link.'<br>';

//$link1=odbc_connect("infracciones","inspecvigil","k5k3d6JdNsEMv8uJ");
//echo 'link '.$link1.'<br>';
?>
